version: "3"
name: "EmeraldApp"

services:
  app:
    container_name: app
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./app/.docker/Dockerfile
    depends_on:
      migrate:
        condition: service_completed_successfully
    command: [ "npm", "run", "start" ]